spring:
  datasource:
    url: jdbc:mysql://localhost/leave?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 # 连接池的初始化大小
      min-idle: 10 #　最小空闲连接数
      max-active: 20 #　最大空闲数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #　访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid



######################################
########### 控制台打印SQL语句
######################################
logging:
  level:
    root: warn
    com.lv.adminsys.modules.dao: trace
  pattern:
    console: '%p%m%n'
