spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lv?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 # 连接池的初始化大小
      min-idle: 10 #　最小空闲连接数
      max-active: 20 #　最大空闲数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #　访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druidtest

  #############################
  ######## redis配置
  #############################
  cache:
    type: redis
  redis:
    host: localhost:
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
server:
  port: 8886
