###########################
######### 模式匹配
##########################
spring:
  profiles:
    # 环境 dev|test|prod
    active: dev
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
    #process-definition-location-suffixes: #流程文件格式
    #  - **.bpmn20.xml


#############################
###### mybatis-plus配置
#############################
mybatis-plus:
  mapper-locations: classpath:mappering/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.lv.adminsys.modules.entity
  global-config:
    db-config:
      table-underline: true
      db-type: mysql

#############################
###### 老师工号前缀配置
#############################
teacher:
  start: T
